---
- name: Installation of Zookeeper Binaries
  apt: name={{ item  }} state=present update_cache=yes
  with_items:
    - zookeeper
    - zookeeper-bin
    - zookeeperd


- name: Delete zookeeper configuration
  file: path={{ item }} state=absent
  with_items:
    - /etc/zookeeper/conf/zoo.cfg
    - /etc/zookeeper/conf/myid

- name: ZooKeeper ID configuration
  template: src=zoo_id.j2 dest=/etc/zookeeper/conf/myid

- name: ZooKeeper Config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  notify:
    - restart zookeeper

- name: Download ZooKeeper archive with client
  get_url: url=http://apache-mirror.rbc.ru/pub/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz dest=~/zookeeper-3.4.6.tar.gz

- name: Unpack ZooKeeper archive
  action: shell tar -xzf ~/zookeeper-3.4.6.tar.gz

#- name: Add to PATH
#  action: shell export PATH=$PATH:~/zookeeper-3.4.6/bin
