---

- hosts: all
  sudo: True
  roles:
    - role: common
    - role: oracle-java
    - role: scala
    - role: sbt

- hosts: zookeeper
  sudo: True
  roles:
    - role: zookeeper

- hosts: mesos_masters
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "master", eth: "eth1"}

- hosts: mesos_workers
  sudo: True
  roles:
    - { role: mesos, mesos_install_mode: "slave", eth: "eth1" }