---
mesos_playbook_version: "0.1.5"

platform_url_name: "ubuntu"
package_type: "deb"

mesos_install_mode: "master" # {master|slave|master-slave}
# used to compose mesos_download_url
mesos_version: "0.19.0"
mesos_arch: "amd64" # alt for >= 13.10 is facter_architecture
mesos_file_name: "mesos_{{mesos_version}}~{{platform_url_name}}{{ansible_distribution_version}}%2B1_{{mesos_arch}}.{{package_type}}"
# mesosphere has different pattern for 0.19.0, see exmaples
#mesos_file_name: "mesos_{{mesos_version}}_{{mesos_arch}}.{{package_type}}"
#http://downloads.mesosphere.io/master/ubuntu/14.04/mesos_0.19.0~ubuntu14.04%2B1_amd64.deb
#http://downloads.mesosphere.io/master/ubuntu/13.10/mesos_0.18.2_amd64.deb
mesos_dest_file: "/tmp/{{mesos_file_name}}"
mesos_python_file_name: "mesos-{{mesos_version}}_rc2-py2.7-linux-x86_64.egg" 
# ditto for python
# http://downloads.mesosphere.io/master/ubuntu/14.04/mesos-0.19.0_rc2-py2.7-linux-x86_64.egg
# http://downloads.mesosphere.io/master/ubuntu/13.10/mesos-0.18.2-py2.7-linux-x86_64.egg
mesos_python_dest_file: "/tmp/{{mesos_python_file_name}}"
mesos_base_url: "http://downloads.mesosphere.io/master"
mesos_download_url: "{{mesos_base_url}}/{{platform_url_name}}/{{ansible_distribution_version}}/{{mesos_file_name}}"
mesos_python_download_url: "{{mesos_base_url}}/{{platform_url_name}}/{{ansible_distribution_version}}/{{mesos_python_file_name}}"

  #http://downloads.mesosphere.io/master/ubuntu/14.04/mesos_0.19.0_amd64.deb

# exec info
mesos_bin_name: mesos
mesos_local_bin: "{{mesos_bin_name}}-local"
mesos_master_bin: "{{mesos_bin_name}}-master"
mesos_slave_bin: "{{mesos_bin_name}}-slave"

# conf file settings
mesos_cluster_name: "mesos_cluster"
mesos_hostname: "{{ inventory_hostname }}"
mesos_log_location: "/var/log/mesos"
mesos_ulimit: "-n 8192"
mesos_options: "--log_dir=$LOGS"
work_dir: "/var/mesos"
mesos_zookeeper: "zk://192.168.99.100:2181,192.168.99.10:2181,192.168.99.11:2181/mesos"
mesos_zookeeper_masters: "zk://192.168.99.100:2181/mesos"
quorum: 2

# Containerizer
isolation: "external"
containerizer_path: "/usr/local/bin/deimos"
