# https://mesosphere.io/docs/getting-started/debian-install/

- include: zookeeper.yml
  when: mesos_install_mode == "master" or mesos_install_mode == "mixed"

- debug: var=group

#- include: mesos.yml