# https://mesosphere.io/docs/getting-started/debian-install/

- name: Add mesosphere repository key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add mesosphere repository
  apt_repository: repo='deb http://repos.mesosphere.io/ubuntu trusty main' state=present

- name: Installation of Mesos
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mesos
    - marathon


- name: Create Mesos workdir
  action: shell mkdir -p /var/lib/mesos

- name: Delete mesos config
  file: path={{ item }} state=absent
  with_items:
    - /etc/default/mesos
    - /etc/default/mesos-master
    - /etc/default/mesos-slave
    - /etc/mesos-master/hostname
    - /etc/mesos-slave/hostname
    - /tmp/mesos/meta

- name: Mesos Default Configuration
  template: src=mesos.j2 dest=/etc/default/mesos

- name: Mesos Master Configuration
  template: src=mesos-master.j2 dest={{ mesos_master_config }}

- name: Mesos Slave Configuration
  template: src=mesos-slave.j2 dest={{ mesos_slave_config }}

- name: Init script patch
  template: src=quorum.j2 dest=/etc/mesos-master/quorum

- name: Copying utility for node IP registration
  template: src=register_ip.sh.j2 dest=/tmp/register_ip.sh mode=755

- name: Registering host external IP in Mesos
  action: shell /tmp/register_ip.sh

- name: Mesos ZK Configuration
  template: src=zk.j2 dest=/etc/mesos/zk
  notify:
    - restart mesos-master
    - restart mesos-slave
    - restart marathon
#
#- name: restart mesos-master
#  service: name=mesos-master state=restarted
#  when: mesos_install_mode == "master" or mesos_install_mode == "mixed"
#
#- name: restart mesos-slave
#  service: name=mesos-slave state=restarted
#  when: mesos_install_mode == "slave" or mesos_install_mode == "mixed"

#- name: restart marathon
#  service: name=marathon state=restarted
#  when: mesos_install_mode == "master" or mesos_install_mode == "mixed"