---
- name: restart mesos-master
  service: name=mesos-master state=restarted
  when: mesos_install_mode == "master"

- name: restart mesos-slave
  service: name=mesos-slave state=restarted
  when: mesos_install_mode == "slave"

- name: restart marathon
  service: name=marathon state=restarted
  when: mesos_install_mode == "master"