---

# Starting Mesos and Marathon
- name: Start Mesos Master
  action: shell sudo /usr/bin/mesos-init-wrapper master &
  when: mesos_install_mode == "master"

- name: Start Mesos Master
  action: shell sudo /usr/bin/mesos-init-wrapper slave &
  when: mesos_install_mode == "slave"

  file: path=/etc/init/mesos-master.conf state=absent
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Delete slave script
  file: path=/etc/init/mesos-slave.conf state=absent
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

# == Re-enable services as necessary
- name: Mesos master script
  template: src=mesos.j2 dest=/etc/init/mesos-master.conf
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-master

- name: Mesos slave script
  template: src=mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-slave
